### ISSUE TITLE
Inline equation paragraph stripping

### ISSUE THREAD

**Issue by summersz** [mbarkhau/markdown-katex#13]
Hi,

Currently if you try to use an inline equation on it's own the postprocessor will strip the paragraph tags added by the markdown processing.
e.g.
```
$`e=mc^2`$

$`y=mx+c`$
```

will have the paragraph tags stripped and render on the same line.

Changing line 300 in extension.py to `if wrapped_marker in text and marker.startswith('tmp_block'):` appears to be a simple fix and works at least for my current usage.

**Comment by mbarkhau** [comment]
Sounds like a plan. You want to do a PR?
