### ISSUE TITLE
Math rendering below the Fenced Code Blocks

### ISSUE THREAD

**Issue by alexanderlarin** [mbarkhau/markdown-katex#3]
## Actual Behavior

Math blocks don't render at all if placed below the Fenced Code Block wrapped with ```` but works fine with another [fenced code block](https://python-markdown.github.io/extensions/fenced_code_blocks/#syntax). For example:
~~~
````
````
$`a^2`$
~~~
doesn't render the equation properly, but the following example works correctly:
````
~~~
~~~
$`a^2`$
````

## Expected Behavior

The markdown block as follows has to render equation:
~~~
````
````
$`a^2`$
~~~

## References

- [Fenced Code Blocks](https://python-markdown.github.io/extensions/fenced_code_blocks/#syntax)

**Comment by mbarkhau** [comment]
At least here you're using four backticks instead of three. Are you using four or three backticks in your project?

**Comment by mbarkhau** [comment]
Upon reading the doc you linked:

> To include a set of backticks (or tildes) within a code block, use a different number of backticks for the deliminators.

Fascinating, I was unaware that this is legitimate syntax.

````
```
code
```
````

Thanks for the report. I'll look into it at some point, but probably not too soon. If you want to work on a PR, let me know.

**Comment by alexanderlarin** [comment]
@mbarkhau thank you for the fast response. I was surprised about that syntax too, but it was used in the project I'm currently working on, and I've decided you need to know about the problem. As workaround, we start using `~~~ ~~~` block.

As to PR I'm not sure that I could help you soon but if I have a time gap I'll notify you.
